name: Publish Docker Image
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: darvid/manylinux-hyperscan
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          snapshot: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
          registry: docker.pkg.github.com
          repository: darvid/manylinux-hyperscan/manylinux-hyperscan
          tag_with_ref: true
