name: Docker Image CI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag docker.pkg.github.com/darvid/manylinux-hyperscan/manylinux-hyperscan:${RELEASE_VERSION}
    - name: Push Docker image to GPR
      run: |
        docker login docker.pkg.github.com -u darvid -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push docker.pkg.github.com/darvid/manylinux-hyperscan/manylinux-hyperscan:${RELEASE_VERSION}
    env:
      GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
